### ISSUE TITLE
isDOM方法不存在

### ISSUE THREAD

**Issue by zhujia1109** [xyl66/vuePlugs_printjs#9]
Error in event handler for "click": "TypeError: this.isDOM is not a function"

found in

---> <ElButton>
       <ElRow>
         <Read> at src/pages/form/engineeringEvent/read.vue
           <App> at src/App.vue
             <Root>

**Comment by chinahub** [comment]
[Vue warn]: Error in event handler for "click": "TypeError: this.isDom is not a function"

**Comment by chinahub** [comment]
doPrintVue () {
      var newstr = document.getElementsByClassName('printOrder-data')[0].innerHTML
      document.body.innerHTML = newstr
      window.print()
      // 重新加载页面，以刷新数据
      window.location.reload()
}
参考：
https://segmentfault.com/q/1010000011527757
https://codepen.io/joseluisq/pen/VzRpGb

**Comment by DAHU123** [comment]
TypeError: this.isDOM is not a function
    at new Print (print.js?7fde:13)
现在我也是遇到了这个问题....求大神支招呀.....

**Comment by a54552239** [comment]
同问

**Comment by xyl66** [comment]
已修复
